
Insert into DEPARTAMENTO (ID,NOMBRE,CODIGO_DANE) values ('19','NORTE DE SANTANDER','54');
commit;
Insert into DEPARTAMENTO (ID,NOMBRE,CODIGO_DANE) values ('20','QUINDIO','63');
commit;
Insert into DEPARTAMENTO (ID,NOMBRE,CODIGO_DANE) values ('21','RISARALDA','66');
commit;
Insert into DEPARTAMENTO (ID,NOMBRE,CODIGO_DANE) values ('22','SANTANDER','68');
commit;
Insert into DEPARTAMENTO (ID,NOMBRE,CODIGO_DANE) values ('7','CALDAS','17');
commit;
Insert into DEPARTAMENTO (ID,NOMBRE,CODIGO_DANE) values ('13','CHOCO','27');
commit;
Insert into DEPARTAMENTO (ID,NOMBRE,CODIGO_DANE) values ('26','ARAUCA','81');
commit;
Insert into DEPARTAMENTO (ID,NOMBRE,CODIGO_DANE) values ('27','CASANARE','85');
commit;
Insert into DEPARTAMENTO (ID,NOMBRE,CODIGO_DANE) values ('16','MAGDALENA','47');
commit;
Insert into DEPARTAMENTO (ID,NOMBRE,CODIGO_DANE) values ('17','META','50');
commit;
Insert into DEPARTAMENTO (ID,NOMBRE,CODIGO_DANE) values ('6','BOYACA','15');
commit;
Insert into DEPARTAMENTO (ID,NOMBRE,CODIGO_DANE) values ('25','VALLE DEL CAUCA','76');
commit;
Insert into DEPARTAMENTO (ID,NOMBRE,CODIGO_DANE) values ('5','BOLIVAR','13');
commit;
Insert into DEPARTAMENTO (ID,NOMBRE,CODIGO_DANE) values ('8','CAQUETA','18');
commit;
Insert into DEPARTAMENTO (ID,NOMBRE,CODIGO_DANE) values ('9','CAUCA','19');
commit;
Insert into DEPARTAMENTO (ID,NOMBRE,CODIGO_DANE) values ('14','HUILA','41');
commit;
Insert into DEPARTAMENTO (ID,NOMBRE,CODIGO_DANE) values ('12','CUNDINAMARCA','25');
commit;
Insert into DEPARTAMENTO (ID,NOMBRE,CODIGO_DANE) values ('10','CESAR','20');
commit;
Insert into DEPARTAMENTO (ID,NOMBRE,CODIGO_DANE) values ('11','CORDOBA','23');
commit;
Insert into DEPARTAMENTO (ID,NOMBRE,CODIGO_DANE) values ('23','SUCRE','70');
commit;
Insert into DEPARTAMENTO (ID,NOMBRE,CODIGO_DANE) values ('24','TOLIMA','73');
commit;
Insert into DEPARTAMENTO (ID,NOMBRE,CODIGO_DANE) values ('18','NARIÑO','52');
commit;
Insert into DEPARTAMENTO (ID,NOMBRE,CODIGO_DANE) values ('33','VAUPES','97');
commit;
Insert into DEPARTAMENTO (ID,NOMBRE,CODIGO_DANE) values ('34','VICHADA','99');
commit;
Insert into DEPARTAMENTO (ID,NOMBRE,CODIGO_DANE) values ('2','ANTIOQUIA','05');
commit;
Insert into DEPARTAMENTO (ID,NOMBRE,CODIGO_DANE) values ('3','ATLANTICO','8');
commit;
Insert into DEPARTAMENTO (ID,NOMBRE,CODIGO_DANE) values ('4','BOGOTA D.C','11');
commit;
Insert into DEPARTAMENTO (ID,NOMBRE,CODIGO_DANE) values ('15','LA GUAJIRA','44');
commit;
Insert into DEPARTAMENTO (ID,NOMBRE,CODIGO_DANE) values ('29','ARCHIPIELAGO DE SAN ANDRES','88');
commit;
Insert into DEPARTAMENTO (ID,NOMBRE,CODIGO_DANE) values ('30','AMAZONAS','91');
commit;
Insert into DEPARTAMENTO (ID,NOMBRE,CODIGO_DANE) values ('31','GUAINIA','94');
commit;
Insert into DEPARTAMENTO (ID,NOMBRE,CODIGO_DANE) values ('32','GUAVIARE','95');
commit;
Insert into DEPARTAMENTO (ID,NOMBRE,CODIGO_DANE) values ('28','PUTUMAYO','86');
commit;

